- name: Build with Buildozer
  run: |
    pip install buildozer cython
    sudo apt update
    sudo apt install -y zip unzip openjdk-17-jdk
    yes | sdkmanager --licenses
    buildozer android debug
